apiVersion: v1
kind: Service
metadata:
  name: logiscripts-userportal-service
spec:
  ports:
    - port: 32000
      nodePort: 32000
      targetPort: logi-userp-port
      protocol: TCP
  selector:
    app: logiscripts-userportal
  type: NodePort
